Reset pass impl
ErunamoJAZZ/web2023-adopta-un-michi pull request #12
Opened 2023-11-23 16:12 UTC by kalixtez

ya pueden roastear

2023-11-23 16:28 UTC, ErunamoJAZZ requested changes
Algunos cambios.

En particular, un tema de estilos (tengo la duda, ¿tiene instalado en ESlint en el VSCode?), cuidado con dejar siempre un enter en la última línea de los archivos, y otras cositas más.

2023-11-23 16:28 UTC, ErunamoJAZZ commented on backend/src/auth.ts
> +function get_rand_token(length: number)
En JS normalmente se hace uso del `camelCase` para las cosas.

El único caso en que se usa `SNAKE_CASE` es para nombrar constantes y variables de entorno. De resto, no se usa.

2023-11-23 16:28 UTC, ErunamoJAZZ commented on backend/src/auth.ts
> +    const pgPool: Pool = require("./index");
No se debe usar el requite, si no que por el contrario, se debe usar siempre la importación en la cabecera. Esto es una mala práctica bajo los estándares actuales para proyectos en Node.

2023-11-23 16:28 UTC, ErunamoJAZZ commented on backend/src/auth.ts
> +          text: `TF is this field for?`, // plain text body
lol, ese comentario qué ome xD
Eso es para algunos clietes de correo, que muestran el texto en formato sencillo en vez de en Html (que ese se presume va a estar enriquecido con más cosas). Algunos por ejemplo, lo usan para mostrar en las notificaciones y así.

2023-11-23 16:28 UTC, ErunamoJAZZ commented on backend/src/index.ts
> +const router = require("./auth");
De nuevo, no se puede usar require, para eso es que existe los imports.

2023-11-23 16:28 UTC, ErunamoJAZZ commented on backend/src/index.ts
> +module.exports = pgPool;
Siempre al final de los archivos, debe quedar un espacio en blanco (o si no, github se queja)

2023-11-23 16:28 UTC, ErunamoJAZZ commented on database/ddl.sql
> +CREATE TABLE michis.user_token (
Hace falta agregar el smart comment para que Postgraphile no genere esta tabla en el GraphQL https://www.graphile.org/postgraphile/smart-tags/#omit
Creo que sería con `@omit read`

2023-11-23 16:28 UTC, ErunamoJAZZ commented on frontend/src/app/login/recoverPassword/page.tsx
> +  const url = "http://localhost:3001";
Esa url, creo que sería mejor si la ponemos como una variable de entorno más.

2023-11-23 16:28 UTC, ErunamoJAZZ commented on frontend/src/app/login/resetPassword/[token]/page.tsx
> +  const url = "http://localhost:3001";
es muy raro que tenga que setear esto en varias partes, haciendo uso de lo de la variable de entorno, no habría necesidad.

2023-11-23 17:53 UTC, kalixtez commented on frontend/src/app/login/recoverPassword/page.tsx
> +  const url = "http://localhost:3001";
Como se hace eso en el cliente? Con contexto o haciendola una variable global o algo asi??

2023-11-23 17:54 UTC, kalixtez commented on backend/src/auth.ts
> +function get_rand_token(length: number)
Esto es mb, ya me lo habian dicho y se me olvido, es que yo siempre programo en snake case, nunca en camel, ya que los lenguajes en los que aprendi a programar (c/c++) el camel y el snake conviven y yo me quede con el snake

2023-11-23 18:21 UTC, ErunamoJAZZ commented on frontend/src/app/login/resetPassword/[token]/page.tsx
> +  const url = "http://localhost:3001";
Literal poniendo un dato en el env para llamarlo con process.env.XXXX

2023-11-24 00:52 UTC, kalixtez commented on frontend/src/app/login/resetPassword/[token]/page.tsx
> +  const url = "http://localhost:3001";
Pero ese codigo es del cliente, del front, si se puede asi?

2023-11-26 02:02 UTC, ErunamoJAZZ approved these changes

2023-11-26 02:02 UTC, ErunamoJAZZ commented on backend/src/auth.ts
> +import { Router } from 'express';
No se debería importar dos veces express, si no que dentro de la misma importación.

2023-11-26 02:14 UTC, ErunamoJAZZ approved these changes

2023-11-26 02:19 UTC, merged